---
jelly_image: lscr.io/linuxserver/jellyfin
jelly_version: latest
jelly_container_name: jelly-media
jelly_volumes: 
  - /mnt/conf/jelly:/config
  - /mnt/data/jelly:/cache
  - /mnt/media/movies:/data/movies
  - /mnt/media/tv:/data/tv
jelly_ports: 8096:8096
jelly_env:
  - PUID=1000
  - PGID=1000
  - TZ=Etc/UTC
jelly_network: media-net

prometheus_image: docker.io/prom/prometheus
prometheus_version: latest
prometheus_container_name: prometheus
prometheus_create_volumes: prometheus-data
prometheus_volumes: 
  - /mnt/conf/prometheus:/etc/prometheus
  - prometheus-data:/prometheus
prometheus_files:
  - { src: "prometheus-basic.yml", dst: "/mnt/conf/prometheus/prometheus.yml" }
prometheus_ports: 9090:9090
prometheus_network: monitoring-net

grafana_image: docker.io/grafana/grafana
grafana_version: latest
grafana_container_name: grafana
grafana_create_volumes: grafana-data
grafana_volumes: 
  - grafana-data:/var/lib/grafana
grafana_ports: 3000:3000
grafana_network: monitoring-net


npm_network: media-net


cadvisor_image: gcr.io/cadvisor/cadvisor
cadvisor_version: latest
cadvisor_container_name: cadvisor
cadvisor_volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
cadvisor_ports: 8080:8080
cadvisor_network: monitoring-net
cadvisor_command: 
  - --disable_metrics=disk,referenced_memory

nodexxporter_image: prom/node-exporter
nodexxporter_version: latest
nodexxporter_container_name: node-exporter
nodexxporter_command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
nodexxporter_volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
nodexxporter_ports: 9100:9100
nodexxporter_network: monitoring-net
nodexxporter_priveleged_run: true