---
- name: Installing Jellyfin image
  hosts: DockerVm
  tags: media
  vars:
    image: "{{ jelly_image }}"
    image_tag: "{{ jelly_version }}"
    container_name: "{{ jelly_container_name }}"
    container_volumes: "{{ jelly_volumes }}"
    container_ports: "{{ jelly_ports }}"
    network_name: "{{ jelly_network }}"
  roles:
    - containers
    - network

- name: Installing Prometheus image
  hosts: DockerVm
  tags: monitoring
  vars:
    image: "{{ prometheus_image }}"
    image_tag: "{{ prometheus_version }}"
    container_name: "{{ prometheus_container_name }}"
    container_volumes: "{{ prometheus_volumes }}"
    container_ports: "{{ prometheus_ports }}"
    volume_name: "{{ prometheus_create_volumes }}"
    network_name: "{{ prometheus_network }}"
    file_destinations: "{{ prometheus_files }}"
  roles:
    - volumes
    - role: files
      become: true
    - containers
    - network

- name: Installing Grafana image
  hosts: DockerVm
  tags: monitoring
  vars:
    image: "{{ grafana_image }}"
    image_tag: "{{ grafana_version }}"
    container_name: "{{ grafana_container_name }}"
    container_volumes: "{{ grafana_volumes }}"
    container_ports: "{{ grafana_ports }}"
    volume_name: "{{ grafana_create_volumes }}"
    network_name: "{{ grafana_network }}"
  roles:
    - volumes
    - containers
    - network

- name: Installing NPM image
  hosts: DockerVm
  tags: nginx
  vars:
    image: jlesage/nginx-proxy-manager
    image_tag: latest
    container_name: npm-deb
    container_volumes: npm-data:/config:rw
    container_ports: 
      - 8181:8181
      - 80:8080
      - 443:4443
    network_name: "{{ npm_network }}"
    volume_name: npm-data
  roles:
    - volumes
    - containers
    - network


