---
- name: Installing Jellyfin image
  hosts: DockerVm
  tags: media
  vars:
    image: "{{ jelly_image }}"
    image_tag: "{{ jelly_version }}"
    container_name: "{{ jelly_container_name }}"
    container_volumes: "{{ jelly_volumes }}"
    container_ports: "{{ jelly_ports }}"
    network_name: "{{ jelly_network }}"
  roles:
    - network
    - containers

- name: Installing NPM image
  hosts: DockerVm
  tags: nginx
  vars:
    image: jlesage/nginx-proxy-manager
    image_tag: latest
    container_name: npm-deb
    container_volumes: npm-data:/config:rw
    container_ports:
      - 8181:8181
      - 80:8080
      - 443:4443
    network_name: "{{ npm_network }}"
    volume_name: npm-data
  roles:
    - volumes
    - containers
    - network