---
- name: Installing Cadvisor image
  hosts: DockerVm
  tags: monitoring, cadvisor
  vars:
    image: "{{ cadvisor_image }}"
    image_tag: "{{ cadvisor_version }}"
    container_name: "{{ cadvisor_container_name }}"
    container_volumes: "{{ cadvisor_volumes }}"
    container_ports: "{{ cadvisor_ports }}"
    network_name: "{{ cadvisor_network }}"
    container_command: "{{ cadvisor_command }}"
  roles:
    - network
    - containers

- name: Installing Node-exporter image
  hosts: DockerVm
  tags: monitoring, node-exporter
  vars:
    image: "{{ nodexxporter_image }}"
    image_tag: "{{ nodexxporter_version }}"
    container_name: "{{ nodexxporter_container_name }}"
    container_volumes: "{{ nodexxporter_volumes }}"
    container_ports: "{{ nodexxporter_ports }}"
    network_name: "{{ nodexxporter_network }}"
    container_command: "{{ nodexxporter_command }}"
    container_priveleged_run: "{{ nodexxporter_priveleged_run }}"
  roles:
    - network
    - containers
    
- name: Installing Prometheus image
  hosts: DockerVm
  tags: monitoring, prometheus
  vars:
    image: "{{ prometheus_image }}"
    image_tag: "{{ prometheus_version }}"
    container_name: "{{ prometheus_container_name }}"
    container_volumes: "{{ prometheus_volumes }}"
    container_ports: "{{ prometheus_ports }}"
    volume_name: "{{ prometheus_create_volumes }}"
    network_name: "{{ prometheus_network }}"
    file_destinations: "{{ prometheus_files }}"
  roles:
    - volumes
    - role: files
      become: true
    - network
    - containers
  handlers:
  - name: Restart prometheus
    ansible.builtin.docker_container:
      name: prometheus
      state: started
      restart: true

- name: Installing Grafana image
  hosts: DockerVm
  tags: monitoring, grafana
  vars:
    image: "{{ grafana_image }}"
    image_tag: "{{ grafana_version }}"
    container_name: "{{ grafana_container_name }}"
    container_volumes: "{{ grafana_volumes }}"
    container_ports: "{{ grafana_ports }}"
    volume_name: "{{ grafana_create_volumes }}"
    network_name: "{{ grafana_network }}"
  roles:
    - volumes
    - network
    - containers