---
- name: "Create docker network: {{ network_name }}"
  ansible.builtin.docker_network:
    name: "{{ network_name }}"
    driver: bridge
    state: present

- name: "Add a container to a network: {{ network_name }}"
  community.docker.docker_network:
    name: "{{ network_name }}"
    connected:
      - "{{ container_name }}"
    appends: true    